// Typed access to src/data/slide-types.json - the slide-type registry as it
// exists in the core repo, generated by scripts/generate-slide-types.js.
//
// Everything here is derived. Nothing about a slide type is written down twice
// on this site: the count, the list, the labels, the field tables, the
// "when to use it" lines and the layout glyphs all come out of core. Editing this
// file cannot change what the site claims - regenerate instead.

import data from '@/data/slide-types.json';
import type { SchematicSpec } from '@/lib/schematic';

export interface SlideTypeField {
  key: string;
  label: string;
  type: string;
  required: boolean;
  maxLength?: number;
  options?: { value: string; label: string }[];
  itemFields?: SlideTypeField[];
}

export interface SlideTypeLayoutVariant {
  id: string;
  label: string;
  schematic: SchematicSpec | null;
}

export interface SlideType {
  /** Bare registry key, and the value in a deck's `slides[].type`. */
  name: string;
  /**
   * The canonical identity: reverse-DNS (`eu.deckyard.slide.title`). It is a
   * second spelling of `name`, never a second type, and storage never moved -
   * `slides[].type` still carries the bare key.
   */
  id: string;
  label: string;
  deprecated: boolean;
  group: SlideTypeGroup;
  /**
   * The shape of the type's primary content, declared in core. `null` when a
   * type declares none - core's own answer, not a default this side invents, so
   * a gap in the facet has to look like a gap.
   */
  structure: SlideStructure | null;
  /**
   * What the presenting session has to do for the type beyond serving it.
   * `null` on the same terms as `structure`: core's own gap, not a default.
   */
  runtime: SlideRuntime | null;
  /**
   * What kind of answer a `live` type collects. `null` on every other runtime,
   * which core asserts in both directions rather than this side assuming.
   */
  interaction: LiveInteraction | null;
  /** How far the promise goes. Everything published here is 1 or 2. */
  tier: SlideTier;
  /**
   * The tier-1 contract to degrade to when a reader has not implemented this
   * type. `null` on a tier-1 type, which is the floor and has nothing below it.
   */
  fallback: string | null;
  /** True when the audience takes part rather than only watching. */
  audience: boolean;
  description: string | null;
  agentDescription: string | null;
  bestFor: string[];
  notFor: string[];
  schematic: SchematicSpec | null;
  layoutVariants: SlideTypeLayoutVariant[];
  /** Type-specific fields. The nine every type carries are in `globalFields`. */
  fields: SlideTypeField[];
}

export type SlideTypeGroup = 'basic' | 'media' | 'layouts' | 'data' | 'interaction' | 'other';

/** Display order, matching the editor's own shelving. */
export const SLIDE_TYPE_GROUPS: SlideTypeGroup[] = [
  'basic',
  'media',
  'layouts',
  'data',
  'interaction',
  'other',
];

/**
 * The `structure` facet's vocabulary. Six values that partition all core types
 * with no "other" bucket, which is core's own evidence that the axis is right.
 *
 * This is a different kind of statement from `SlideTypeGroup` above. A group is
 * the editor's shelving and mixes four axes - `basic` is familiarity, `media`
 * and `data` are payload, `interaction` is runtime behaviour - so it says where
 * a type sits in a picker, not what its content looks like. `structure` is a
 * claim about the content shape, derivable from the field schema and guarded by
 * a test in core, which is why the spec page groups by it and the picker's
 * groups stay out of the spec entirely.
 */
export type SlideStructure =
  'singleton' | 'collection' | 'fixed-collection' | 'tabular' | 'dataset' | 'chrome';

export interface SlideStructureEntry {
  name: SlideStructure;
  /** The one-line meaning, as core words it. */
  meaning: string;
}

/**
 * The `runtime` facet: what the presenting session has to do for a slide type
 * beyond serving it.
 *
 * A different question from `structure`, and answered a different way.
 * `structure` is about the content and is derivable from the field schema, so a
 * declaration that lies is catchable by a test. `runtime` is a fact about the
 * server that nothing in the schema can confirm, so core guards it from the
 * other end: no module may re-derive the live set by hand, which is the
 * measurement that produced the facet in the first place.
 *
 * The line is drawn at *session state*, not at "has behaviour". That is what
 * makes `countdown-slide` `timed` rather than `live`, and `lead-capture-slide`
 * `static` even though it plainly collects from the room - its submissions go
 * to lead storage over their own endpoint and never reach the session.
 */
export type SlideRuntime = 'static' | 'timed' | 'live';

/** The kind of answer a `live` type collects. Meaningless on any other runtime. */
export type LiveInteraction = 'poll' | 'likert' | 'feedback';

/**
 * The tier ladder, and the only one of the three facets that is a *promise*
 * rather than a description. Tier 1 is normative; tier 2 we ship and publish but
 * it versions with the app; tier 3 is a fork's or a third party's declaration,
 * so nothing published from core carries it.
 */
export type SlideTier = 1 | 2 | 3;

export interface SlideRuntimeEntry {
  name: SlideRuntime;
  meaning: string;
}

export interface LiveInteractionEntry {
  name: LiveInteraction;
  meaning: string;
}

export interface SlideTierEntry {
  tier: SlideTier;
  meaning: string;
}

const registry = data as unknown as {
  count: number;
  activeCount: number;
  deprecatedCount: number;
  structures: SlideStructureEntry[];
  runtimes: SlideRuntimeEntry[];
  interactions: LiveInteractionEntry[];
  tiers: SlideTierEntry[];
  coreProfile: string[];
  globalFields: SlideTypeField[];
  types: SlideType[];
};

export const slideTypes: SlideType[] = registry.types;
export const globalFields: SlideTypeField[] = registry.globalFields;

/** Built-in slide types in core. Excludes anything a fork adds locally. */
export const slideTypeCount = registry.count;
export const slideTypeActiveCount = registry.activeCount;
export const slideTypeDeprecatedCount = registry.deprecatedCount;

/** How many types let the audience take part - the figure that sets it apart. */
export const slideTypeAudienceCount = slideTypes.filter((t) => t.audience && !t.deprecated).length;

/** Active types in a group, in registration order. */
export function typesInGroup(group: SlideTypeGroup): SlideType[] {
  return slideTypes.filter((t) => t.group === group && !t.deprecated);
}

/** The four types kept only so existing decks keep rendering. */
export const deprecatedTypes: SlideType[] = slideTypes.filter((t) => t.deprecated);

// ---------------------------------------------------------------------------
// The `structure` facet
// ---------------------------------------------------------------------------

/** The vocabulary, in core's declaration order. */
export const slideStructures: SlideStructureEntry[] = registry.structures;

/** Active types declaring a structure, in registration order. */
export function typesWithStructure(structure: SlideStructure): SlideType[] {
  return slideTypes.filter((t) => t.structure === structure && !t.deprecated);
}

/**
 * A type's repeating fields: the ones carrying an item shape rather than a
 * scalar. This is what makes the shared contract of a `collection` visible -
 * twelve types, one array of homogeneous items each, so one renderer covers
 * all twelve.
 *
 * Read off the field table rather than asserted, which is what lets the page
 * show where the declaration and the schema disagree instead of smoothing it
 * over: `poll-slide` and `likert-slide` declare `fixed-collection` and carry
 * `option1..optionN` as scalars, so they come back empty here. Core tracks both
 * in an open burndown; a page that hid them would be claiming a tidier format
 * than the one on offer.
 */
export function repeatingFields(type: SlideType): SlideTypeField[] {
  return type.fields.filter((f) => Array.isArray(f.itemFields) && f.itemFields.length > 0);
}

/**
 * How many active types a reader covers by implementing a set of structures.
 * This is the number that turns "we support Deckyard decks" into a claim with
 * an edge: a renderer that does singleton and collection can say so and name
 * what it skips, instead of choosing between all thirty-six and silence.
 */
export function structureCoverage(structures: SlideStructure[]): number {
  const wanted = new Set(structures);
  return slideTypes.filter((t) => !t.deprecated && t.structure && wanted.has(t.structure)).length;
}

// ---------------------------------------------------------------------------
// The `runtime` facet
// ---------------------------------------------------------------------------

/** The vocabulary, in core's declaration order. */
export const slideRuntimes: SlideRuntimeEntry[] = registry.runtimes;

/** The three answer kinds a `live` type can declare. */
export const liveInteractions: LiveInteractionEntry[] = registry.interactions;

/** Active types with a given runtime, in registration order. */
export function typesWithRuntime(runtime: SlideRuntime): SlideType[] {
  return slideTypes.filter((t) => t.runtime === runtime && !t.deprecated);
}

// ---------------------------------------------------------------------------
// Tiers and the fallback map
// ---------------------------------------------------------------------------

/** The tier vocabulary, as core states it. */
export const slideTiers: SlideTierEntry[] = registry.tiers;

/**
 * The nine normative types, in core's order rather than sorted. The order is
 * the argument: title, section break, prose, enumeration, quotation, image,
 * image-with-text, table, closing is a presentation read start to end.
 */
export const coreProfile: SlideType[] = registry.coreProfile
  .map((name) => slideTypes.find((t) => t.name === name))
  .filter((t): t is SlideType => Boolean(t));

/** Active types in a tier, in registration order. */
export function typesInTier(tier: SlideTier): SlideType[] {
  return slideTypes.filter((t) => t.tier === tier && !t.deprecated);
}

/**
 * Every tier-1 type with the tier-2 types that degrade to it. This is the whole
 * argument of the tier split in one data structure: five of the nine absorb all
 * twenty-seven of the rest, so a reader that implements only the core profile
 * still renders every deck without dropping content.
 *
 * Built from the declarations rather than from a hand-kept list, so a tier-2
 * type that ever loses its `fallback` disappears from a column here instead of
 * being quietly counted in one.
 */
export function fallbackMap(): { target: SlideType; sources: SlideType[] }[] {
  return coreProfile
    .map((target) => ({
      target,
      sources: slideTypes.filter((t) => !t.deprecated && t.fallback === target.name),
    }))
    .filter((row) => row.sources.length > 0);
}

/**
 * Active tier-2 types that declare no fallback. Expected to be empty, and shown
 * rather than assumed: the claim "every tier-2 type declares one" is only worth
 * making on a page that would visibly break if it stopped being true.
 */
export function unmappedTypes(): SlideType[] {
  return slideTypes.filter((t) => !t.deprecated && t.tier === 2 && !t.fallback);
}
