// Typed access to src/data/slide-types.json - the slide-type registry as it
// exists in the core repo, generated by scripts/generate-slide-types.js.
//
// Everything here is derived. Nothing about a slide type is written down twice
// on this site: the count, the list, the labels, the field tables, the
// "when to use it" lines and the layout glyphs all come out of core. Editing this
// file cannot change what the site claims - regenerate instead.

import data from '@/data/slide-types.json';
import type { SchematicSpec } from '@/lib/schematic';

export interface SlideTypeField {
  key: string;
  label: string;
  type: string;
  required: boolean;
  maxLength?: number;
  options?: { value: string; label: string }[];
  itemFields?: SlideTypeField[];
}

export interface SlideTypeLayoutVariant {
  id: string;
  label: string;
  schematic: SchematicSpec | null;
}

export interface SlideType {
  /** Bare registry key, and the value in a deck's `slides[].type`. */
  name: string;
  /** Qualified identity: `namespace/name[@version]`. */
  id: string;
  label: string;
  deprecated: boolean;
  group: SlideTypeGroup;
  /**
   * The shape of the type's primary content, declared in core. `null` when a
   * type declares none - core's own answer, not a default this side invents, so
   * a gap in the facet has to look like a gap.
   */
  structure: SlideStructure | null;
  /**
   * What the presenting session has to do for the type beyond serving it.
   * `null` on the same terms as `structure`: core's own gap, not a default.
   */
  runtime: SlideRuntime | null;
  /**
   * What kind of answer a `live` type collects. `null` on every other runtime,
   * which core's guardrail asserts rather than this side assuming.
   */
  interaction: LiveInteraction | null;
  /** True when the audience takes part rather than only watching. */
  audience: boolean;
  description: string | null;
  agentDescription: string | null;
  bestFor: string[];
  notFor: string[];
  schematic: SchematicSpec | null;
  layoutVariants: SlideTypeLayoutVariant[];
  /** Type-specific fields. The nine every type carries are in `globalFields`. */
  fields: SlideTypeField[];
}

export type SlideTypeGroup = 'basic' | 'media' | 'layouts' | 'data' | 'interaction' | 'other';

/** Display order, matching the editor's own shelving. */
export const SLIDE_TYPE_GROUPS: SlideTypeGroup[] = [
  'basic',
  'media',
  'layouts',
  'data',
  'interaction',
  'other',
];

/**
 * The `structure` facet's vocabulary. Six values that partition all core types
 * with no "other" bucket, which is core's own evidence that the axis is right.
 *
 * This is a different kind of statement from `SlideTypeGroup` above. A group is
 * the editor's shelving and mixes four axes - `basic` is familiarity, `media`
 * and `data` are payload, `interaction` is runtime behaviour - so it says where
 * a type sits in a picker, not what its content looks like. `structure` is a
 * claim about the content shape, derivable from the field schema and guarded by
 * a test in core, which is why the spec page groups by it and the picker's
 * groups stay out of the spec entirely.
 */
export type SlideStructure =
  'singleton' | 'collection' | 'fixed-collection' | 'tabular' | 'dataset' | 'chrome';

export interface SlideStructureEntry {
  name: SlideStructure;
  /** The one-line meaning, as core words it. */
  meaning: string;
}

/**
 * The `runtime` facet's vocabulary: what the presenting session has to do for a
 * slide type beyond serving it.
 *
 * The second facet, and it answers a different question from `structure`.
 * `structure` is about the content and is derivable from the field schema;
 * `runtime` is a fact about the server, which nothing in the schema can confirm,
 * so core guards it from the other end - no module may re-derive the live set by
 * hand, which is the measurement that produced the facet in the first place.
 *
 * The line is drawn at *session state*, not at "has behaviour". That is what
 * makes `countdown-slide` `timed` rather than `live`, and `lead-capture-slide`
 * `static` even though it plainly collects from the room: its submissions go to
 * lead storage over their own endpoint and never reach the session.
 */
export type SlideRuntime = 'static' | 'timed' | 'live';

/** The kind of answer a `live` type collects. Meaningless on any other runtime. */
export type LiveInteraction = 'poll' | 'likert' | 'feedback';

export interface SlideRuntimeEntry {
  name: SlideRuntime;
  meaning: string;
}

export interface LiveInteractionEntry {
  name: LiveInteraction;
  meaning: string;
}

const registry = data as unknown as {
  count: number;
  activeCount: number;
  deprecatedCount: number;
  structures: SlideStructureEntry[];
  runtimes: SlideRuntimeEntry[];
  interactions: LiveInteractionEntry[];
  globalFields: SlideTypeField[];
  types: SlideType[];
};

export const slideTypes: SlideType[] = registry.types;
export const globalFields: SlideTypeField[] = registry.globalFields;

/** Built-in slide types in core. Excludes anything a fork adds locally. */
export const slideTypeCount = registry.count;
export const slideTypeActiveCount = registry.activeCount;
export const slideTypeDeprecatedCount = registry.deprecatedCount;

/** How many types let the audience take part - the figure that sets it apart. */
export const slideTypeAudienceCount = slideTypes.filter((t) => t.audience && !t.deprecated).length;

/** Active types in a group, in registration order. */
export function typesInGroup(group: SlideTypeGroup): SlideType[] {
  return slideTypes.filter((t) => t.group === group && !t.deprecated);
}

/** The four types kept only so existing decks keep rendering. */
export const deprecatedTypes: SlideType[] = slideTypes.filter((t) => t.deprecated);

// ---------------------------------------------------------------------------
// The `structure` facet
// ---------------------------------------------------------------------------

/** The vocabulary, in core's declaration order. */
export const slideStructures: SlideStructureEntry[] = registry.structures;

/** Active types declaring a structure, in registration order. */
export function typesWithStructure(structure: SlideStructure): SlideType[] {
  return slideTypes.filter((t) => t.structure === structure && !t.deprecated);
}

/**
 * A type's repeating fields: the ones carrying an item shape rather than a
 * scalar. This is what makes the shared contract of a `collection` visible -
 * twelve types, one array of homogeneous items each, so one renderer covers
 * all twelve.
 *
 * Read off the field table rather than asserted, which is what lets the page
 * show where the declaration and the schema disagree instead of smoothing it
 * over: `poll-slide` and `likert-slide` declare `fixed-collection` and carry
 * `option1..optionN` as scalars, so they come back empty here. Core tracks both
 * in an open burndown; a page that hid them would be claiming a tidier format
 * than the one on offer.
 */
export function repeatingFields(type: SlideType): SlideTypeField[] {
  return type.fields.filter((f) => Array.isArray(f.itemFields) && f.itemFields.length > 0);
}

/**
 * How many active types a reader covers by implementing a set of structures.
 * This is the number that turns "we support Deckyard decks" into a claim with
 * an edge: a renderer that does singleton and collection can say so and name
 * what it skips, instead of choosing between all thirty-eight and silence.
 */
export function structureCoverage(structures: SlideStructure[]): number {
  const wanted = new Set(structures);
  return slideTypes.filter((t) => !t.deprecated && t.structure && wanted.has(t.structure)).length;
}

// ---------------------------------------------------------------------------
// The `runtime` facet
// ---------------------------------------------------------------------------

/** The vocabulary, in core's declaration order: static, timed, live. */
export const slideRuntimes: SlideRuntimeEntry[] = registry.runtimes;

/** The three answer kinds a `live` type can declare. */
export const liveInteractions: LiveInteractionEntry[] = registry.interactions;

/** Active types with this runtime, in registration order. */
export function typesWithRuntime(runtime: SlideRuntime): SlideType[] {
  return slideTypes.filter((t) => t.runtime === runtime && !t.deprecated);
}

/**
 * Every type with this runtime, retired ones included.
 *
 * The page states both figures where it counts implementation cost, and they are
 * not the same: 28 of the 33 types you can add today are `static`, but 33 of all
 * 38 are, because all five retired types are. A renderer meets retired types in
 * real decks - that is the entire reason they still render - so the wider figure
 * is the honest one for "how much of this needs a session", and the narrower one
 * matches every other count on the page. Neither is typed out anywhere.
 */
export function runtimeCountAll(runtime: SlideRuntime): number {
  return slideTypes.filter((t) => t.runtime === runtime).length;
}

/** Active `live` types collecting this kind of answer. */
export function typesWithInteraction(interaction: LiveInteraction): SlideType[] {
  return slideTypes.filter((t) => t.interaction === interaction && !t.deprecated);
}

/**
 * How many active types a reader covers by implementing a set of structures
 * *and* a set of runtimes - the grid cell, rather than either axis alone.
 *
 * This is what makes the conformance claim both precise and reachable. Structure
 * alone says a renderer walks the content; adding the runtime axis says whether
 * it needs a session server behind it, and the answer for the large majority of
 * the catalogue is no. Narrowing on both is a smaller number than structure
 * alone, which is the point: it is a claim with an edge instead of a boast.
 */
export function coverage(structures: SlideStructure[], runtimes: SlideRuntime[]): number {
  const wantedStructures = new Set(structures);
  const wantedRuntimes = new Set(runtimes);
  return slideTypes.filter(
    (t) =>
      !t.deprecated &&
      t.structure &&
      wantedStructures.has(t.structure) &&
      t.runtime &&
      wantedRuntimes.has(t.runtime)
  ).length;
}
